/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intranet;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;

/**
 *
 * @author 2class-004
 */
public class IntraLogin extends javax.swing.JFrame {

    /**
     * Creates new form IntraLogin
     */
	Intra intra;
	LoginDAO lDao=new LoginDAO();
	EmpDAO eDao=new EmpDAO();
	DeptDAO dDao=new DeptDAO();
	ArrayList<LoginVO> empLoginList=null; 
	ArrayList<DeptVO> allDeptList=null;
	EmpVO owner;
	Msg msg;

	public IntraLogin() {
        initComponents();
        
		// 회사 전체 사원번호, 사원이름, pwd 가져오기
        empLoginList=lDao.listLoginEmp();
        allDeptList=dDao.listDept();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogin = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbEmpid = new javax.swing.JLabel();
        tfEmpid = new javax.swing.JTextField();
        lbPwd = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLogin.setBackground(new java.awt.Color(121, 176, 215));

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/companyLogo_L.jpg"))); // NOI18N

        lbEmpid.setText("ID(사번)");

        lbPwd.setText("패스워드");

        tfPwd.setText("");

        btLogin.setText("로그인");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        lbInfo.setText("※비밀번호 분실 시 관리부(02-000-0000, admin@company.com)에 별도 문의※");

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addGap(0, 340, Short.MAX_VALUE)
                .addComponent(lbInfo)
                .addGap(323, 323, 323))
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmpid)
                    .addComponent(lbPwd))
                .addGap(18, 18, 18)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(tfEmpid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                        .addComponent(lbLogo)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                        .addComponent(btLogin)
                        .addGap(494, 494, 494))))
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(lbLogo)
                .addGap(57, 57, 57)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpid)
                    .addComponent(tfEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPwd))
                .addGap(34, 34, 34)
                .addComponent(btLogin)
                .addGap(35, 35, 35)
                .addComponent(lbInfo)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    public void loginNullCheck(String id, String pwd) {
    	if(id==null||id.trim().isEmpty()) {
    		JOptionPane.showMessageDialog(null, "id를 다시 입력해 주세요.");
    		return;
    	}
    	if(pwd==null|pwd.trim().isEmpty()) {
    		JOptionPane.showMessageDialog(null, "패스워드를 다시 입력해 주세요.");
    	}
    }
	
	public int LoginCheck(int empId, String pwd) {
        for(int i=0;i<empLoginList.size();i++) {
        	LoginVO user=empLoginList.get(i);
			if (user.getEmpId() == empId) {
				if (pwd.equals(user.getPwd())) {			// 패스워드 체크
					owner=eDao.findLoginEmp(empId);
					if (owner.getDeptNo()==100) return 9; 	// 관리자 모드
					else return 2;							// 일반 사용자 모드
				}
				return 1;
			}
        }
        return 0;
	}	
    
	/**intra 창 띄우기*/
    public void popUp() {
    	this.dispose();
		intra.pack();
		intra.setLocation(0,0);
		intra.setVisible(true);
    }
    
    /**로그인 버튼*/
    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	String inputtedEmpString=tfEmpid.getText();
    	int flag=-1;
    	try {
    		int inputtedEmpId=Integer.parseInt(inputtedEmpString.trim());
    		char[] pwd=tfPwd.getPassword();
    		String inputtedPwd=new String(pwd);
    		loginNullCheck(inputtedEmpString, inputtedPwd);
    		flag=LoginCheck(inputtedEmpId, inputtedPwd);
		} catch (Exception e) {
			e.getMessage();
			e.printStackTrace();
		}
		if (flag > 1) {
			JOptionPane.showMessageDialog(null, owner.getEmpId() + "(" + owner.geteName()+")님 환영합니다.");
			if (flag == 9)
				JOptionPane.showMessageDialog(null, "관리자 모드로 이용 가능합니다.");
			if (msg==null) msg=new Msg(owner);
			intra=new Intra(owner,msg,allDeptList);
			popUp();	
		} else if (flag == 1) {
			JOptionPane.showMessageDialog(null, "비밀번호를 재확인해 주세요.");
		} else {
			JOptionPane.showMessageDialog(null, "등록된 사원번호가 아닙니다. 사원번호를 정확히 입력바랍니다.");
		}
		
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntraLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel lbEmpid;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPwd;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JTextField tfEmpid;
    private javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
